/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 34
#define YY_END_OF_BUFFER 35
static yyconst short int yy_accept[223] =
    {   0,
        0,    0,   35,   33,   30,   31,   32,   33,   33,   27,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   33,    0,   27,   25,    0,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   24,   29,   29,
       26,    0,    0,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,    0,    0,   22,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,    0,    0,   29,   29,   29,   29,   29,   12,

       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,    0,    0,   20,   29,   29,   29,   29,
       29,   29,   29,   29,    7,    9,   29,   29,   29,   29,
       29,   29,   29,   29,    0,   11,   29,   29,   29,   29,
       29,   29,   10,   13,    8,   29,   29,   29,   29,   29,
       29,    0,    0,    6,   29,   29,   29,   29,   23,   29,
       29,   29,   29,   29,   29,    0,   29,   17,   18,   19,
       29,   29,   29,    4,   29,   29,   28,   29,   29,   29,
       29,   29,   29,   28,   28,   14,   29,   29,   29,   29,
        5,   29,   29,    2,   29,    3,   29,   29,    1,   29,

       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   21,   29,   29,   29,   29,   29,   29,   15,
       16,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    1,    5,    1,    1,    1,    1,    6,
        6,    7,    1,    6,    8,    9,   10,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,    1,    1,    1,
        6,    1,    1,    1,   12,   13,   14,   15,   16,   17,
       18,   19,   20,   21,   21,   22,   23,   24,   25,   26,
       21,   27,   28,   29,   30,   31,   21,   21,   32,   21,
        1,    1,    1,    1,   33,    1,   21,   21,   21,   21,

       34,   21,   21,   21,   35,   21,   21,   36,   21,   37,
       21,   21,   21,   21,   21,   21,   21,   38,   21,   21,
       21,   21,    6,    1,    6,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[39] =
    {   0,
        1,    1,    1,    2,    1,    1,    1,    1,    3,    1,
        3,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4
    } ;

static yyconst short int yy_base[228] =
    {   0,
        0,  157,  153,  692,  692,  131,  692,  129,  122,   31,
       32,   35,   39,   36,   44,   40,   48,   51,   58,   62,
       63,   67,   68,   71,   75,   85,   89,   77,  692,   97,
        0,   90,   91,   94,   95,   98,  101,  102,  107,  116,
      117,  121,  124,  125,  128,  132,  135,  139,  147,  152,
      143,   61,   80,  156,  157,  160,  161,  164,  168,  169,
      178,  179,  184,  185,  189,  190,  193,  197,  194,  204,
      208,   53,   73,  209,  212,  220,  225,  215,  229,  234,
      237,  241,  245,  246,  250,  254,  255,  260,  261,  266,
      267,  276,   47,  287,  283,  284,  287,  294,  297,  291,

      303,  306,  307,  310,  311,  315,  316,  319,  323,  332,
      333,  338,  341,   59,  351,  692,  347,  348,  351,  354,
      357,  358,  363,  367,  368,  372,  375,  380,  385,  389,
      394,  395,  398,  401,  199,  404,  405,  408,  411,  422,
      415,  426,  429,  430,  433,  434,  437,  438,  441,  445,
      450,   43,  456,  460,  463,  464,  467,  470,  473,  474,
      480,  481,  488,  489,  493,   36,  496,  497,  500,  504,
      505,  508,  512,  513,  516,  519,  520,  528,  529,  533,
      536,  537,  542,    0,  543,  549,  550,  553,  557,  558,
      562,  563,  566,  567,  575,  576,  583,  587,  590,  594,

      597,  601,  604,  605,  608,  609,  612,  613,  627,  619,
      631,  635,  636,  639,  642,  643,  646,  652,  656,  647,
      661,  692,  678,  680,  683,  685,  687
    } ;

static yyconst short int yy_def[228] =
    {   0,
      222,    1,  222,  222,  222,  222,  222,  222,  222,  222,
      223,  223,  223,  223,  223,  223,  223,  223,  223,  223,
      223,  223,  223,  223,  223,  222,  222,  222,  222,  222,
      224,  223,  223,  223,  223,  223,  223,  223,  223,  223,
      223,  223,  223,  223,  223,  223,  223,  223,  223,  223,
      224,  222,  222,  223,  223,  223,  223,  223,  223,  223,
      223,  223,  223,  223,  223,  223,  223,  223,  223,  223,
      223,  222,  222,  223,  223,  223,  223,  223,  223,  223,
      223,  223,  223,  223,  223,  223,  223,  223,  223,  223,
      223,  223,  222,  222,  223,  223,  223,  223,  223,  223,

      223,  223,  223,  223,  223,  223,  223,  223,  223,  223,
      223,  223,  223,  222,  222,  222,  223,  223,  223,  223,
      223,  223,  223,  223,  223,  223,  223,  223,  223,  223,
      223,  223,  223,  223,  222,  223,  223,  223,  223,  223,
      223,  223,  223,  223,  223,  223,  223,  223,  223,  223,
      223,  222,  222,  223,  223,  223,  223,  223,  223,  223,
      223,  223,  223,  223,  223,  225,  223,  223,  223,  223,
      223,  223,  223,  223,  223,  223,  226,  223,  223,  223,
      223,  223,  223,  227,  226,  223,  223,  223,  223,  223,
      223,  223,  223,  223,  223,  223,  223,  223,  223,  223,

      223,  223,  223,  223,  223,  223,  223,  223,  223,  223,
      223,  223,  223,  223,  223,  223,  223,  223,  223,  223,
      223,    0,  222,  222,  222,  222,  222
    } ;

static yyconst short int yy_nxt[731] =
    {   0,
        4,    5,    6,    5,    4,    7,    4,    8,    7,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   16,   18,
       16,   19,   20,   16,   21,   22,   16,   23,   24,   16,
       25,   16,   16,   16,   16,   16,   16,   25,   30,  166,
       31,   28,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   38,   31,  153,   31,   39,   31,   35,   31,   31,
       33,   31,  135,   36,   34,   37,   31,   40,   31,   41,
       31,   31,   31,   31,   42,   31,   31,   31,   31,   31,
      114,   31,   43,   51,   30,   51,   44,   28,   94,   93,
       48,   46,   45,   47,   73,   72,   49,   50,   31,   31,

       31,   31,   31,   31,   31,   31,   31,   28,   31,   31,
       31,   31,   31,   53,   56,   31,   58,   31,   60,   54,
       52,   57,   55,   59,   31,   31,   31,   31,   29,   31,
       61,   31,   31,   31,   31,   31,   31,   64,   31,   28,
       31,   62,   31,   31,   27,   31,   63,   31,   65,   31,
       68,   51,  222,   51,   69,   31,   66,   31,   70,   67,
       31,   26,   31,   71,   31,   31,   31,   31,   31,   31,
       31,   31,   31,  222,   31,   78,   31,   31,   31,   31,
      222,   76,   74,   79,   77,   75,   31,   31,   31,   31,
       80,   82,   31,   31,   31,   31,   84,   31,   31,   31,

       31,   31,   31,   31,   31,   31,  152,   31,   85,  153,
       81,   88,   31,   83,   31,   86,   31,   31,   31,   31,
       31,   87,   31,   31,   90,   31,  222,  222,   31,   89,
       31,   92,   91,   31,   96,   31,   95,   31,  222,   31,
       97,  222,   31,   98,   31,   31,  222,   31,  102,   31,
      222,   31,  103,   31,   31,   31,   31,   99,   31,  222,
       31,  100,   31,   31,   31,   31,  101,  105,   31,   31,
       31,   31,  110,  104,   31,   31,   31,   31,  106,  109,
      222,  222,  112,  107,   31,  222,   31,  108,  115,  116,
      115,   31,   31,   31,   31,   31,  222,   31,  111,   31,

      119,   31,   31,  113,   31,   31,  117,   31,  222,  120,
      118,   31,  121,   31,   31,   31,   31,   31,   31,   31,
       31,   31,  122,   31,   31,   31,   31,   31,  124,   31,
      129,   31,  222,   31,  123,  222,  130,  125,  126,  127,
       31,   31,   31,   31,  128,  131,   31,  132,   31,   31,
      222,   31,  115,  116,  115,   31,   31,   31,   31,   31,
      134,   31,   31,  137,   31,   31,   31,   31,   31,  222,
      133,   31,  222,   31,  136,   31,   31,   31,   31,  138,
       31,  141,   31,   31,  222,   31,  139,  222,   31,  140,
       31,  142,  222,   31,  143,   31,  222,   31,  146,   31,

      147,  144,   31,   31,   31,   31,   31,  145,   31,   31,
      149,   31,   31,   31,   31,   31,   31,  222,   31,   31,
      150,   31,  148,   31,  156,   31,  222,  155,  154,  151,
       31,  158,   31,  222,   31,  157,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
      222,   31,  159,   31,  163,   31,  164,  162,   31,  166,
       31,  222,  160,  152,  222,  161,  153,  222,   31,  165,
       31,   31,   31,   31,   31,   31,  168,   31,   31,  169,
       31,   31,   31,   31,   31,  222,  222,  167,   31,   31,
       31,   31,  222,  171,  170,  172,   31,   31,   31,   31,

      222,   31,  175,   31,   31,   31,   31,   31,   31,  174,
       31,  173,   31,   31,   31,   31,   31,  176,   31,  178,
       31,   31,   31,   31,   31,  222,   31,   31,  184,   31,
      184,  181,  222,  222,  182,  179,   31,   31,   31,   31,
      180,   31,  183,   31,   31,   31,   31,   31,  187,  188,
       31,  184,   31,  184,  222,  186,  190,   31,   31,   31,
       31,   31,  222,   31,  189,   31,   31,   31,   31,  191,
       31,   31,   31,   31,   31,   31,   31,   31,  192,  222,
      222,  195,  193,   31,   31,   31,   31,  222,  194,  197,
      199,   31,  222,   31,  196,   31,  201,   31,   31,  198,

       31,  222,   31,  202,   31,   31,  222,   31,  200,   31,
      203,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   31,   31,  207,  204,  211,   31,  222,   31,
      205,  208,  209,  206,  222,   31,  210,   31,  222,   31,
      212,   31,  213,   31,   31,   31,   31,   31,  222,   31,
       31,   31,   31,   31,   31,   31,   31,   31,  216,  214,
       31,  217,   31,  215,   31,  222,   31,  218,  222,   31,
      219,   31,  222,  222,  222,  220,  222,  222,  222,  221,
       32,   32,   31,   31,  177,  222,  177,  185,  185,  184,
      184,    3,  222,  222,  222,  222,  222,  222,  222,  222,

      222,  222,  222,  222,  222,  222,  222,  222,  222,  222,
      222,  222,  222,  222,  222,  222,  222,  222,  222,  222,
      222,  222,  222,  222,  222,  222,  222,  222,  222,  222
    } ;

static yyconst short int yy_chk[731] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,   10,  166,
       11,   10,   11,   12,   14,   12,   14,   13,   16,   13,
       16,   14,   15,  152,   15,   14,   17,   13,   17,   18,
       11,   18,  114,   13,   12,   13,   19,   15,   19,   17,
       20,   21,   20,   21,   18,   22,   23,   22,   23,   24,
       93,   24,   19,   25,   28,   25,   20,   28,   73,   72,
       23,   22,   21,   22,   53,   52,   23,   24,   32,   33,

       32,   33,   34,   35,   34,   35,   36,   30,   36,   37,
       38,   37,   38,   27,   35,   39,   37,   39,   39,   33,
       26,   36,   34,   38,   40,   41,   40,   41,    9,   42,
       40,   42,   43,   44,   43,   44,   45,   43,   45,    8,
       46,   41,   46,   47,    6,   47,   42,   48,   44,   48,
       47,   51,    3,   51,   47,   49,   45,   49,   49,   46,
       50,    2,   50,   50,   54,   55,   54,   55,   56,   57,
       56,   57,   58,    0,   58,   58,   59,   60,   59,   60,
        0,   56,   54,   59,   57,   55,   61,   62,   61,   62,
       60,   62,   63,   64,   63,   64,   64,   65,   66,   65,

       66,   67,   69,   67,   69,   68,  135,   68,   65,  135,
       61,   68,   70,   63,   70,   66,   71,   74,   71,   74,
       75,   67,   75,   78,   69,   78,    0,    0,   76,   68,
       76,   71,   70,   77,   76,   77,   75,   79,    0,   79,
       77,    0,   80,   78,   80,   81,    0,   81,   81,   82,
        0,   82,   82,   83,   84,   83,   84,   79,   85,    0,
       85,   80,   86,   87,   86,   87,   80,   84,   88,   89,
       88,   89,   89,   83,   90,   91,   90,   91,   85,   88,
        0,    0,   91,   86,   92,    0,   92,   87,   94,   94,
       94,   95,   96,   95,   96,   97,    0,   97,   90,  100,

       97,  100,   98,   92,   98,   99,   95,   99,    0,   98,
       96,  101,   99,  101,  102,  103,  102,  103,  104,  105,
      104,  105,  101,  106,  107,  106,  107,  108,  103,  108,
      108,  109,    0,  109,  102,    0,  109,  104,  105,  106,
      110,  111,  110,  111,  107,  110,  112,  111,  112,  113,
        0,  113,  115,  115,  115,  117,  118,  117,  118,  119,
      113,  119,  120,  118,  120,  121,  122,  121,  122,    0,
      112,  123,    0,  123,  117,  124,  125,  124,  125,  119,
      126,  122,  126,  127,    0,  127,  120,    0,  128,  121,
      128,  123,    0,  129,  124,  129,    0,  130,  129,  130,

      130,  127,  131,  132,  131,  132,  133,  128,  133,  134,
      132,  134,  136,  137,  136,  137,  138,    0,  138,  139,
      133,  139,  131,  141,  139,  141,    0,  138,  137,  134,
      140,  141,  140,    0,  142,  140,  142,  143,  144,  143,
      144,  145,  146,  145,  146,  147,  148,  147,  148,  149,
        0,  149,  142,  150,  149,  150,  150,  148,  151,  153,
      151,    0,  146,  153,    0,  147,  153,    0,  154,  151,
      154,  155,  156,  155,  156,  157,  156,  157,  158,  157,
      158,  159,  160,  159,  160,    0,    0,  155,  161,  162,
      161,  162,    0,  160,  158,  161,  163,  164,  163,  164,

        0,  165,  164,  165,  167,  168,  167,  168,  169,  163,
      169,  162,  170,  171,  170,  171,  172,  165,  172,  167,
      173,  174,  173,  174,  175,    0,  175,  176,  177,  176,
      177,  173,    0,    0,  175,  171,  178,  179,  178,  179,
      172,  180,  176,  180,  181,  182,  181,  182,  179,  180,
      183,  185,  183,  185,    0,  178,  182,  186,  187,  186,
      187,  188,    0,  188,  181,  189,  190,  189,  190,  183,
      191,  192,  191,  192,  193,  194,  193,  194,  187,    0,
        0,  190,  188,  195,  196,  195,  196,    0,  189,  193,
      195,  197,    0,  197,  192,  198,  197,  198,  199,  194,

      199,    0,  200,  198,  200,  201,    0,  201,  196,  202,
      200,  202,  203,  204,  203,  204,  205,  206,  205,  206,
      207,  208,  207,  208,  204,  201,  208,  210,    0,  210,
      202,  205,  206,  203,    0,  209,  207,  209,    0,  211,
      209,  211,  210,  212,  213,  212,  213,  214,    0,  214,
      215,  216,  215,  216,  217,  220,  217,  220,  214,  211,
      218,  215,  218,  212,  219,    0,  219,  216,    0,  221,
      217,  221,    0,    0,    0,  218,    0,    0,    0,  219,
      223,  223,  224,  224,  225,    0,  225,  226,  226,  227,
      227,  222,  222,  222,  222,  222,  222,  222,  222,  222,

      222,  222,  222,  222,  222,  222,  222,  222,  222,  222,
      222,  222,  222,  222,  222,  222,  222,  222,  222,  222,
      222,  222,  222,  222,  222,  222,  222,  222,  222,  222
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexan.l"
#define INITIAL 0
#line 7 "lexan.l"

/*****************************************************************************
 *
 * (C) Copyright 1998 by National Advanced Driving Simulator and
 * Simulation Center, the University of Iowa and The University
 * of Iowa. All rights reserved.
 *
 * Version:      $Id: lexan.l,v 1.8 2016/10/28 20:58:28 IOWA\dheitbri Exp $
 *
 * Author:       Yiannis Papelis
 * Date:         November, 1995
 *
 * Description:  Lex file that produced the lexical analyzer to use with 
 *               the hcsm parser.
 *
 ****************************************************************************/
#include <stdlib.h>
#include <setjmp.h>
#include "parser.h"

static int  max_size           = 0;    /* max size of g_LargeTokVal memory */
static int  cur_size           = 0;    /* current size of g_LargeTokVal */
#pragma warning(disable:4996)
/**********************************************************************
 *
 * This function 'swallows' all C style comments.  They are not
 * saved anywhere.
 *
 */
void skipcommnts(void)
{
	char c;

	while ( 1 ) {
		while ( (c=input()) != '*' )  {
			if ( c == '\n' )
				g_LineNum++;
			if ( c == 0 ) {
				fprintf(stderr, "***** Lexan warning: found unclosed comment.\n" );
				return;
			}
		}

		if ( (c=input()) == '/' ) {
			return;
		}
#if 0
		else
			yyunput(c);
#endif
	}
}


/**********************************************************************
 *
 * This function appends characters to a string buffer.  It will extend
 * the buffer as needed to accommodate arbitrary size strings.  It
 * always zero terminates the string.
 *
 */
static void append_char( int c)
{
	if ( cur_size + 2 >= max_size ) {
		max_size += 4096;
		g_LargeTokVal = (char *)realloc(g_LargeTokVal, max_size);
		if ( g_LargeTokVal == NULL ) {
			fprintf(stderr, "Lexical analyzer run out of memory\n");
			exit(-1);
		}
	}
	g_LargeTokVal[cur_size++] = c;
	g_LargeTokVal[cur_size]   = '\0';
}


/**********************************************************************
 *
 * This function consumes the remainder of the input line and puts
 * it in the g_LargeTokVal buffer.
 *
 */
void consume_remainder_of_line(void)
{
	int  c;

	if ( g_LargeTokVal != NULL ) {
		free(g_LargeTokVal);
		g_LargeTokVal = NULL;
		max_size = cur_size = 0;
	}

	while ( 1 ) {
		c = input();
		append_char(c);
		if ( c == '\n' ) {
			g_LineNum++;
			break;
		}
	}
}

#line 699 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		yy_current_buffer->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 111 "lexan.l"


#line 856 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 223 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 692 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 113 "lexan.l"
return STATEM_TOK;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 114 "lexan.l"
return PRE_ACTIVITY_TOK;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 115 "lexan.l"
return POST_ACTIVITY_TOK;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 116 "lexan.l"
return PRIV_DECL_TOK;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 117 "lexan.l"
return TRANSITIONS_TOK;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 118 "lexan.l"
return CHILDREN_TOK;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 119 "lexan.l"
return INPUTS_TOK;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 120 "lexan.l"
return OUTPUTS_TOK;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 121 "lexan.l"
return LOCALS_TOK;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 122 "lexan.l"
return GLOBALS_TOK;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 123 "lexan.l"
return BUTTONS_TOK;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 124 "lexan.l"
return DIALS_TOK;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 125 "lexan.l"
return MONITORS_TOK;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 126 "lexan.l"
return CONNECTIONS_TOK;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 127 "lexan.l"
return PRE_ACTIVITY_FUNC_TOK;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 128 "lexan.l"
return POST_ACTIVITY_FUNC_TOK;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 129 "lexan.l"
return CREATE_CB_TOK;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 130 "lexan.l"
return DELETE_CB_TOK;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 131 "lexan.l"
return DIAL_INFO_TOK;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 132 "lexan.l"
{ 

/*
 * This piece of code 'swallows' all characters between CODE and
 * &&&&ENDCODE.  Puts them in a dynamic buffer referenced by the
 * variable g_LargeTokVal.
 */
	int  c;              /* single lookahead      */
	int  la;             /* lookahead index       */
	int  pb;             /* putback index         */
	char la_buf[20];     /* lookahead buffer      */
	char tok[] = "&&&&ENDCODE"; /* token to catch */
	int  found_end;      /* boolean               */

	g_LineNum += 2;
/*
 * free memory if variable has been used
 */
	if ( g_LargeTokVal != NULL ) {
		free(g_LargeTokVal);
		max_size = cur_size = 0;
		g_LargeTokVal = NULL;
	}

/*
 * The loop goes until EOF or until the &&&&ENDCODE token is found,
 * we have to by-pass lex to avoid overflowing yytext, and since this
 * is more than one char lookahead
 */
	c  = input();
	while ( 1 ) {

		if ( c <= 0  )  return 0;
		
		if ( c == '\n' ) {    /* if a CR check for end token */

			g_LineNum++;
			found_end = 1;

			for ( la = 0; la < sizeof(tok)-1; la++ ) {

				la_buf[la] = input();

				if ( la_buf[la] != tok[la] ) {

					/* didn't find end, use chars */
					append_char('\n');

					if ( !( la == 0 && la_buf[0] == '\n') ) {

						for ( pb=0; pb <= la; pb++ ) {
							append_char( la_buf[pb] );
						}

					}

					found_end = 0;
					break;

				}
			}

/* 
 * found the end token, just return 
 */
			if ( found_end ) {     
				append_char('\n');
				return CODE_TOK;
			}

/*
 * if we simply skipped a line, save the CR since the next line could
 * be our end token
 */
			if ( la == 0 && la_buf[0] == '\n' ) {
				c = '\n';
				continue;
			}
		}
		else {  /* if not a CR simply append it to the g_LargeTokVal */
			append_char(c);
		}
		c = input(); /* get next char */
	}
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 217 "lexan.l"
return PREDICATE_FUNC_TOK;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 218 "lexan.l"
return ATTR_TOK;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 219 "lexan.l"
return END_ATTR_TOK;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 220 "lexan.l"
return INIT_MARKER_TOK;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 221 "lexan.l"
skipcommnts();
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 222 "lexan.l"
return VERSION_TOK;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 223 "lexan.l"
return POS_INT;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 224 "lexan.l"
{
							sscanf(yytext, "#line %d %s", &g_LineNum, 
											g_CurFile);
							g_LineNum--;
						  }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 229 "lexan.l"
return IDENT;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 230 "lexan.l"
;                  /* these we need to ignore */
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 231 "lexan.l"
g_LineNum++;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 232 "lexan.l"
return yytext[0];  /* these we need as tokens */
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 233 "lexan.l"
return yytext[0];  /* these we need to catch */
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 234 "lexan.l"
ECHO;
	YY_BREAK
#line 1198 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 223 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 223 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 222);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	yy_current_buffer->yy_at_bol = (c == '\n');

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 234 "lexan.l"

